/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{html,js}"
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        sakura: {
          "primary": "#EC4899",
          "primary-focus": "#DB2777",
          "primary-content": "#FFFFFF",
          "secondary": "#F472B6",
          "accent": "#9333EA",
          "neutral": "#374151",
          "base-100": "#FFF5F8",
          "base-200": "#FCE7F3",
          "base-300": "#FBCFE8",
          "base-content": "#831843",
          "info": "#38BDF8",
          "success": "#4ADE80",
          "warning": "#FBBF24",
          "error": "#F87171",
        },
        emerald: {
          "primary": "#10B981",
          "primary-focus": "#059669",
          "primary-content": "#FFFFFF",
          "secondary": "#34D399",
          "accent": "#0284C7",
          "neutral": "#1F2937",
          "base-100": "#F0FDF4",
          "base-200": "#DCFCE7",
          "base-300": "#BBF7D0",
          "base-content": "#064E3B",
          "info": "#0EA5E9",
          "success": "#10B981",
          "warning": "#F59E0B",
          "error": "#EF4444",
        },
        ocean: {
          "primary": "#2563EB",
          "primary-focus": "#1D4ED8",
          "primary-content": "#FFFFFF",
          "secondary": "#3B82F6",
          "accent": "#06B6D4",
          "neutral": "#1E293B",
          "base-100": "#F0F9FF",
          "base-200": "#E0F2FE",
          "base-300": "#BAE6FD",
          "base-content": "#0C4A6E",
          "info": "#38BDF8",
          "success": "#22C55E",
          "warning": "#F59E0B",
          "error": "#EF4444",
        },
        obsidian: {
          "primary": "#8B5CF6",
          "primary-focus": "#7C3AED",
          "primary-content": "#FFFFFF",
          "secondary": "#06B6D4",
          "accent": "#F43F5E",
          "neutral": "#0F172A",
          "base-100": "#090D16",
          "base-200": "#0F172A",
          "base-300": "#1E293B",
          "base-content": "#F8FAFC",
          "info": "#38BDF8",
          "success": "#34D399",
          "warning": "#FBBF24",
          "error": "#FB7185",
        },
        amber: {
          "primary": "#D97706",
          "primary-focus": "#B45309",
          "primary-content": "#FFFFFF",
          "secondary": "#F59E0B",
          "accent": "#EA580C",
          "neutral": "#374151",
          "base-100": "#FFFBEB",
          "base-200": "#FEF3C7",
          "base-300": "#FDE68A",
          "base-content": "#78350F",
          "info": "#0284C7",
          "success": "#16A34A",
          "warning": "#D97706",
          "error": "#DC2626",
        },
      },
    ],
  },
}
